// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table users {
    id integer [primary key]
    user_id char
    username varchar
    role_id char
    created_at dataetime [not null, default: `now()`]
    updated_at datetime
    deleted_at datetime
}

Table roles {
    id integer [primary key]
    rolename varchar
    created_at datetimee [not null, default: `now()`]
    updated_at datetime
    deleted_at datetime
}
Ref user_role:  roles.id >users.role_id

Table projects {
    id integer [primary key]
    created_at dataetime [not null, default: `now()`]
    updated_at datetime
    deleted_at datetime
}

Table screens {
    id integer [primary key]
    created_at dataetime [not null, default: `now()`]
    updated_at datetime
    deleted_at datetime
}

Table features {
    id integer [primary key]
    created_at dataetime [not null, default: `now()`]
    updated_at datetime
    deleted_at datetime
}

Table testcases {
    id integer [primary key]
    created_at dataetime [not null, default: `now()`]
    updated_at datetime
    deleted_at datetime
}

Table testtresults {
    id integer [primary key]
    created_at dataetime [not null, default: `now()`]
    updated_at datetime
    deleted_at datetime
}

Table bugs {
    id integer [primary key]
    created_at dataetime [not null, default: `now()`]
    updated_at datetime
    deleted_at datetime
}

Table buglinks {
    id integer [primary key]
    created_at dataetime [not null, default: `now()`]
    updated_at datetime
    deleted_at datetime
}